### ISSUE TITLE
Handling Bitwarden

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lfops#159]
It would be nice if a playbook containing roles that require bitwarden would tell you in advance if the credential manager isn't available, and exit.

**Comment by NavidSassan** [comment]
I don't think this is possible, as we mostly use bitwarden in the inventory variables which are only evaluated once they are used in the roles themselves

**Comment by markuslf** [comment]
Hmmm... and by using pre_tasks like this in a playbook?

```
pre_tasks:
  - name: 'Ensure Bitwarden serve is already running'
    shell: "pgrep --full 'bw serve'"
    register: 'bw_proc'
    failed_when: 'bw_proc.rc != 0'
    changed_when: false
```
