### ISSUE TITLE
role:php: On CentOS 7, Role tries to install PHP 5.4

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/lfops#85]
Before running LFOps, if you try to do the command below manually (like the role does to ensure that PHP is installed), everything on the CentOS 7 machine running PHP 7.4 is ok:

```
yum install php php-fpm

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
remi                                                                                            | 3.0 kB  00:00:00     
remi-php74                                                                                      | 3.0 kB  00:00:00     
Package php-7.4.30-1.el7.remi.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package php-fpm.x86_64 0:7.4.30-1.el7.remi will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=======================================================================================================================
 Package                  Arch                    Version                            Repository                   Size
=======================================================================================================================
Installing:
 php-fpm                  x86_64                  7.4.30-1.el7.remi                  remi-php74                  1.8 M

Transaction Summary
=======================================================================================================================
Install  1 Package

Total download size: 1.8 M
Installed size: 6.2 M
Is this ok [y/d/N]: 
```

After running the php role, if you check the machine manually:

```
yum install php php-fpm

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Package matching php-5.4.45-19.el7.remi.x86_64 already installed. Checking for update.
Resolving Dependencies
--> Running transaction check
---> Package php-fpm.x86_64 0:5.4.45-19.el7.remi will be installed
--> Processing Dependency: php-common(x86-64) = 5.4.45-19.el7.remi for package: php-fpm-5.4.45-19.el7.remi.x86_64
--> Finished Dependency Resolution
Error: Package: php-fpm-5.4.45-19.el7.remi.x86_64 (remi)
           Requires: php-common(x86-64) = 5.4.45-19.el7.remi
           Installed: php-common-7.4.30-1.el7.remi.x86_64 (@remi-php74)
               php-common(x86-64) = 7.4.30-1.el7.remi
           Available: php-common-5.4.16-48.el7.x86_64 (base)
               php-common(x86-64) = 5.4.16-48.el7
           Available: php-common-5.4.45-18.el7.remi.x86_64 (remi)
               php-common(x86-64) = 5.4.45-18.el7.remi
           Available: php-common-5.4.45-19.el7.remi.x86_64 (remi)
               php-common(x86-64) = 5.4.45-19.el7.remi
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Means: On the second run, the role fails.

This can be fixed by doing manually
```
yum-config-manager --disable 'remi-php*'
yum-config-manager --enable   remi-php74
```

`repo_remi__enabled_php_version: 'php74'` is set.

**Comment by NavidSassan** [comment]
so you manually installed the remi repo and enabled the correct version, but then after running the php (only the role? or the whole playbook?), php 5.4 was on the server?

**Comment by markuslf** [comment]
Happened on 038, web03. We tried to adjust `php__ini_opcache_interned_strings_buffer__host_var`.

On the host (CentOS 7.9):

```
php__ini_opcache_interned_strings_buffer__host_var: 20
php__modules__host_var:
  - name: 'php-gd'
    state: 'present'
  - name: 'php-mbstring'
    state: 'present'
  - name: 'php-mysql'
    state: 'present'
  - name: 'php-opcache'
    state: 'present'
  - name: 'php-pecl-imagick'
    state: 'present'
  - name: 'php-pecl-zip'
    state: 'present'
  - name: 'php-xml'
    state: 'present'

repo_remi__enabled_php_version: 'php74'
```

After that, running `ansible-playbook --inventory ... linuxfabrik.lfops.php` leads to the above mentioned problems (while the role tries to ensure that php is installed). We then fixed the problems by manually running

```
yum-config-manager --disable 'remi-php*'
yum-config-manager --enable   remi-php74

```
